-- This migration was originally generated as a duplicate of 1_add_transfer_status
-- (diffed against a live database that already matched the target schema).
-- No schema changes were actually needed; kept as an empty migration to
-- preserve migration history consistency with the live database's
-- _prisma_migrations table, where it is recorded as applied.